# Generated by Django 3.1.4 on 2021-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Price', models.CharField(max_length=255)),
                ('Details', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog Detail',
                'db_table': 'Blog Detail',
            },
        ),
    ]
