# Generated by Django 3.1.4 on 2021-05-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_blogdetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Blog',
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'UserDetail',
                'db_table': 'UserDetail',
            },
        ),
        migrations.DeleteModel(
            name='blogDetails',
        ),
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.userdetails'),
        ),
    ]
